language: scala
scala:
- 2.10.0
jdk:
- openjdk7
- oraclejdk7

services:
- mongodb
- memcache

env:
- PLAY_VERSION=2.1.1

before_script:
- wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-  sbt test

notifications:
email: false